version: "3.4"

services:
  nodeapp:
    container_name: node_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "80:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - node-webapp-network 
  

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - .docker/data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=chat-app
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge


  # db:
  #   image: mongo
  #   volumes:
  #     - .docker/data/db:/data/db
  #   restart: unless-stopped
  
  # redis:
  #   image: redis:5-alpine
  #   volumes:
  #     - .docker/data/redis:/data
  #   restart: unless-stopped
